rm(list = ls())

tryCatch(setwd("~/Dropbox/HSE/10/missing/application/angrist-evans-1998/"), error = function(e) return(NULL))

library(haven)
d <- read_sas("m_d_806.sas7bdat")
d <- as.data.frame(d)
d.labs <- lapply(d, attributes)
for (i in 1:ncol(d)) {
  d[, i] <- as.numeric(d[, i])
  attributes(d[, i]) <- d.labs[[i]]
}
saveRDS(d, file = "pums80.rds", compress = "xz")

d1 <- read_sas("m_d_903.sas7bdat")
d1 <- as.data.frame(d1)
d1.labs <- lapply(d1, attributes)
for (i in 1:ncol(d1)) {
  d1[, i] <- as.numeric(d1[, i])
  attributes(d1[, i]) <- d1.labs[[i]]
}
saveRDS(d1, file = "pums90.rds", compress = "xz")


d1.labs <- lapply(d, function(x) attributes(x))

setwd("~/Dropbox/HSE/10/missing/application/angrist-evans-1998/")
cores <- 4


d <- readRDS("pums80.rds")
e <- readRDS("pums90.rds")
sort(colnames(d))
sort(colnames(e))


d$MULTI2ND <- as.integer(d$AGEQ2ND == d$AGEQ3RD)
d$MULTI2ND[is.na(d$MULTI2ND)] <- 0
d$ILLEGIT <- 0
d$YOM <- d$DOM_Q <- d$DO1B_Q <- NA

# Computing the status of illegitimate kids
table(d$QTRMAR)
this.cond <- d$QTRMAR > 0
mean(this.cond)
d$QTRMAR[this.cond] <- d$QTRMAR[this.cond] - 1
d$YOM[this.cond & (d$QTRBTHM <= d$QTRMAR)] <- (d$YOBM + d$AGEMAR)[this.cond & (d$QTRBTHM <= d$QTRMAR)]
d$YOM[this.cond & (d$QTRBTHM > d$QTRMAR)] <- (d$YOBM + d$AGEMAR + 1)[this.cond & (d$QTRBTHM > d$QTRMAR)]
d$DOM_Q[this.cond] <- (d$YOM + d$QTRMAR/4)[this.cond]
d$DO1B_Q[this.cond] <- (d$YOBK + d$QTRBKID/4)[this.cond]
d$ILLEGIT[this.cond & (d$DOM_Q - d$DO1B_Q > 0)] <- 1

# Constructing the sexes of the 1st two kids
d$BOY1ST <- as.integer(d$SEXK == 0)
d$BOY2ND <- as.integer(d$SEX2ND == 0)
d$BOYS2 <- as.integer((d$SEXK == 0) & (d$SEX2ND == 0))
d$GIRLS2 <- as.integer((d$SEXK == 1) & (d$SEX2ND == 1))
d$SAMESEX <- as.integer((d$BOYS2 == 1) | (d$GIRLS2 == 1))
d$MOREKIDS <- as.integer(d$KIDCOUNT > 2)
attributes(d$BOY1ST) <- list(label = "first birth boy")
attributes(d$SAMESEX) <- list(label = "first two kids are of same sex")
attributes(d$MOREKIDS) <- list(label = "had more than 2 kids")
attributes(d$BOYS2) <- list(label = "first two births boys")
attributes(d$GIRLS2) <- list(label = "first two births girls")

d$BLACKM <- as.integer(d$RACEM == 2)
d$HISPM <- as.integer(d$RACEM == 12)
d$WHITEM <- as.integer(d$RACEM == 1)
d$OTHRACEM <- 1 - d$BLACKM - d$HISPM - d$WHITEM
d$BLACKD <- as.integer(d$RACED == 2)
d$HISPD <- as.integer(d$RACED == 12)
d$WHITED <- as.integer(d$RACED == 1)
d$OTHRACED <- 1 - d$BLACKD - d$HISPD - d$WHITED
d$NWHITEM <- d$OTHRACEM + d$BLACKM + d$HISPM

attributes(d$BLACKM) <- list(label = "1 if black mother")
attributes(d$HISPM) <- list(label = "1 if Hispanic mother")
attributes(d$OTHRACEM) <- list(label = "1 if other race mother (white is ref)")
attributes(d$BLACKD) <- list(label = "1 if black father")
attributes(d$HISPD) <- list(label = "1 if hispanic father")
attributes(d$OTHRACED) <- list(label = "1 if other race father (white is ref)")

# Education stuff
d$EDUCM <- ifelse(d$FINGRADM %in% 1:2, d$GRADEM-2, d$GRADEM - 3)
d$EDUCM[d$EDUCM < 0] <- 0
attributes(d$EDUCM) <- list(label = "mother's education")

d$HSGRAD <- as.integer(d$EDUCM == 12)
d$HSORMORE <- as.integer(d$EDUCM >= 12)
d$MORETHS <- as.integer(d$EDUCM > 12)

# get ages of mom and dad;
# plus ages when 1st kid was born;

d$AGEM1 <- d$AGEM
d$AGED1 <- d$AGED
attributes(d$AGEM1) <- list(label = "age in years of mom")
attributes(d$AGED1) <- list(label = "age in years of dad")

d$YOBD <- ifelse(d$QTRBTHD == 0, 80 - d$AGED, 79 - d$AGED)

d$AGEQM <- 4*(80-d$YOBM) - d$QTRBTHM - 1
d$AGEQD <- 4*(80-d$YOBD) - d$QTRBTHD
d$AGEFSTM <- trunc((d$AGEQM - d$AGEQK)/4)
d$AGEFSTD <- trunc((d$AGEQD - d$AGEQK)/4)
attributes(d$AGEFSTD) <- list(label = "age of dad when kid first born")
attributes(d$AGEFSTM) <- list(label = "age of mom when kid first born")

# Calculate mother and father's labour supply variables
d$WEEKSM1 <- d$WEEKSM
d$WEEKSD1 <- d$WEEKSD

d$WORKEDM <- as.integer(d$WEEKSM > 0)
d$WORKEDD <- as.integer(d$WEEKSD > 0)
d$WORKEDD[is.na(d$WORKEDD)] <- 0

d$HOURSWD <- d$HOURSD
d$HOURSWM <- d$HOURSM

d$INCOMED <- d$INCOME1D + pmax(0, d$INCOME2D)
d$INCOMEM <- d$INCOME1M + pmax(0, d$INCOME2M)
# ** deflate wages **
defl <- 2.099173554
d$INCOMEM <- d$INCOMEM * defl
d$INCOMED <- d$INCOMED * defl

d$FAMINC1 <- d$FAMINC * defl
d$FAMINCL <- log(pmax(d$FAMINC1, 1))
d$NONMOMI <- d$FAMINC1 - d$INCOME1M * defl
d$NONMOMIL <- log(pmax(1, d$NONMOMI))

attributes(d$WEEKSM1) <- list(label = "weeks worked mom")
attributes(d$WORKEDM) <- list(label = "mom worked last year")
attributes(d$WEEKSD1) <- list(label = "weeks worked dad")
attributes(d$WORKEDD) <- list(label = "dad worked last year")
attributes(d$FAMINCL) <- list(label = "log family income")
attributes(d$AGEFSTM) <- list(label = "age of mom at first birth")
attributes(d$NONMOMI) <- list(label = "income not generated by mom")
attributes(d$INCOMED) <- list(label = "dads labor income")
attributes(d$INCOMEM) <- list(label = "moms labor income")
attributes(d$FAMINC1) <- list(label = "family income")
attributes(d$HOURSWD) <- list(label = "hours of work per week, dad")
attributes(d$HOURSWM) <- list(label = "hours of work per week, mom")


# *** compute age-corrected effects *****
#  1. approx age of 3rd
# 2. compute corrected morekids;

attributes(d$AGEQK) <- list(label = "age of first kid in qtrs")
attributes(d$AGEQ2ND) <- list(label = "age of second kid in qtrs")
attributes(d$AGEQ3RD) <- list(label = "age of 3rd kid in qtrs")

# if morekids=0 then ageq3rdk=0;
table(d$MOREKIDS, useNA = "always")
d$AGEQ3RDK <- as.integer(d$MOREKIDS == 0)
d$MOREA3 <- d$MOREKIDS * d$AGEQ3RDK

d$QOBM <- d$QTRBTHM
d$MSAMPLE <- 0

d$MSAMPLE[!is.na(d$AGED) & d$TIMESMAR == 1 & d$MARITAL == 0 & d$ILLEGIT == 0 & d$AGEFSTD >= 15 & d$AGEFSTM >= 15] <- 1

keep.vars <- c("KIDCOUNT", "MOREKIDS", "BOYS2", "GIRLS2", "BOY1ST", "SAMESEX", "MULTI2ND", "AGEM", "AGEM1", "AGEFSTM",
               "BLACKM", "HISPM", "OTHRACEM", "NWHITEM", "WORKEDM", "WEEKSM1", "HOURSWM", "INCOMEM", "FAMINC1", "NONMOMI", "FAMINCL",
               "NONMOMIL", "AGED1", "AGEFSTD", "MORETHS", "BOY2ND", "MSAMPLE", "EDUCM", "MORETHS", "HSORMORE", "HSGRAD",
               "ASEX", "AAGE", "AQTRBRTH", "ASEX2ND", "AAGE2ND", "BLACKD", "HISPD", "OTHRACED", "WORKEDD", "WEEKSD1",
               "HOURSWD", "INCOMED", "MARITAL", "AGEQ2ND", "AGEQK", "AGEQ3RD", "MOREA3", "AGEQM", "YOBM", "QOBM", "RACEM")
d <- d[, keep.vars]
int.vars <- sapply(d, function(x) isTRUE(all.equal(as.numeric(x), round(x))))
d[which(int.vars)] <- lapply(d[which(int.vars)], as.integer)
twoa <- d[(d$AGEM1 >= 21 & d$AGEM1 <= 35) & d$KIDCOUNT >= 2 & d$AGEQ2ND > 4 & d$AGEFSTM >= 15 & d$ASEX == 0 & d$AAGE == 0 & d$AQTRBRTH ==0 & d$ASEX2ND == 0 & d$AAGE2ND == 0 & d$AQTRBRTH == 0, ]

saveRDS(twoa, "pums80-twoa.rds", compress = "xz")

e <- e[e$AGEM >= 21 & e$AGEM <= 35, ]
e <- e[e$KIDCOUNT >= 2, ]
e <- e[e$AGE2NDK >= 1, ]
e <- e[e$AAGE == 0 & e$AAGE2ND == 0 & e$ASEX == 0 & e$ASEX2ND == 0, ]
e$FERTDIF <- e$KIDCOUNT - (e$FERTIL-1)
e$AGEFSTM <- e$AGEM - e$AGEK
e <- e[e$AGEFSTM >= 15, ]
e <- e[e$PWGTM1 > 0, ]
e$SAMESEX <- e$SEXK == e$SEX2NDK
e$MOREKIDS <- e$KIDCOUNT > 2

e$BLACKM <- as.integer(e$RACEM == 2)
e$WHITEM <- as.integer(e$RACEM == 1)
# e$OTHRACEM <- 1 - e$BLACKM - e$HISPM - e$WHITEM

e$BOY1ST <- as.integer(e$SEXK == 0)
e$BOY2ND <- as.integer(e$SEX2ND == 0)
e$BOYS2 <- as.integer((e$SEXK == 0) & (e$SEX2ND == 0))
e$GIRLS2 <- as.integer((e$SEXK == 1) & (e$SEX2ND == 1))
e$SAMESEX <- as.integer((e$BOYS2 == 1) | (e$GIRLS2 == 1))
e$MOREKIDS <- as.integer(e$KIDCOUNT > 2)

e$INCOMEM <- e$INCOMEM1 + e$INCOMEM2 +e$INCOMEM6
e$NWHITEM <- as.integer(e$RACEM != 1)
e$WORKEDM <- as.integer(e$WEEK89M > 0)
e$WEEKSM1 <- e$WEEK89M
e$HOURSWM <- e$HOUR89M
e$INCOMEM <- e$INCOMEM1 + pmax(0, e$INCOMEM2) + pmax(0, e$INCOMEM6)
e$FAMINCL <- log(pmax(e$FAMINC, 1))

# e$MSAMPLE <- as.integer(!is.na(e$AGED) & e$TIMESMAR == 1 & e$MARITAL == 0 & e$ILLEGIT == 0 & e$AGEFSTD >= 15 & e$AGEFSTM >= 15)
e$MSAMPLE <- as.integer(!is.na(e$AGED) & e$MARITAL == 0 & e$AGEFSTM >= 15)

onea <- e
int.vars2 <- sapply(onea, function(x) isTRUE(all.equal(as.numeric(x), round(x))))
e[which(int.vars2)] <- lapply(e[which(int.vars2)], as.integer)
saveRDS(onea, "pums90-onea.rds", compress = "xz")


summary(twoa)
summary(onea)
nchar(colnames(twoa))
nchar(colnames(onea))
printLikeSAS <- function(x) {
  n <- sprintf("%7d", sum(!is.na(x)))
  m <- sprintf("%6.7f", round(mean(x, na.rm = TRUE), 7))
  s <- sprintf("%6.7f", sd(x, na.rm = TRUE))
  return(list(n = n, mean = m, sd = s))
}

sum.vars <- c("KIDCOUNT", "MOREKIDS", "BOY1ST", "BOY2ND", "BOYS2", "GIRLS2", "SAMESEX", "MULTI2ND",
              "AGEM1", "AGED1", "AGEFSTM", "AGEFSTD", "WORKEDM", "WORKEDD", "WEEKSM1", "WEEKSD1",
              "HOURSWM","HOURSWD", "INCOMEM", "INCOMED", "FAMINC1", "NONMOMI")

cat("Means of full sample: table 2, column 1; 1980 pums")
for (v in sum.vars) {
  a <- printLikeSAS(twoa[, v])
  cat(v, rep(" ", 12 - nchar(v)), a$n, "  ", rep(" ", 15 - nchar(a$mean)), a$mean, rep(" ", 15 - nchar(a$sd)), a$sd, "\n", sep = "")
}

cat("Means of full sample: table 2, column 2; 1990 pums")
for (v in colnames(onea)) {
  a <- printLikeSAS(onea[, v])
  cat(v, rep(" ", 12 - nchar(v)), a$n, "  ", rep(" ", 15 - nchar(a$mean)), a$mean, rep(" ", 15 - nchar(a$sd)), a$sd, "\n", sep = "")
}

twob <- twoa[twoa$MSAMPLE == 1, ]
cat("Means of married sample: table 2, column 2; 1980 pums")
for (v in sum.vars) {
  a <- printLikeSAS(twob[, v])
  cat(v, rep(" ", 12 - nchar(v)), a$n, "  ", rep(" ", 15 - nchar(a$mean)), a$mean, rep(" ", 15 - nchar(a$sd)), a$sd, "\n", sep = "")
}; rm(a)

